name: Data Preprocessing Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  preprocess:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy scikit-learn imbalanced-learn matplotlib seaborn

    - name: Run Preprocessing Script
      run: |
        # Debugging: List files to understand structure
        ls -R
        
        # Menjalankan script (kembalikan ke path relative root jika folder preprocessing ada di root repo)
        python preprocessing/automate_Moch-Arief-Kresnanda.py

    - name: Commit and Push Processed Data
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        # Add folder submission (Coba add dari dalam folder eksperimen jika script menyimpannya di sana)
        git add Eksperimen_SML_Moch-Arief-Kresnanda/preprocessing/bank_marketing_preprocessing/ || git add preprocessing/bank_marketing_preprocessing/
        
        # Add folder .workflow (agar reviewer lihat)
        git add .workflow/preprocessing.yml
        
        # Commit jika ada perubahan
        git commit -m "Auto-update: Processed datasets & Submission structure" || echo "No changes to commit"
        git push
